### ISSUE TITLE
User Schema

### ISSUE THREAD

**Issue by liquidsurfer** [didx-xyz/yoma#37]
id: string | null;
  email: string;
  emailConfirmed: boolean;
  firstName: string;
  surname: string;
  displayName: string | null;
  phoneNumber: string | null;
  countryId: string | null;
  countryOfResidenceId: string | null;
  genderId: string | null;
  dateOfBirth: string | null;
  photoId: string | null;
  photoURL: string | null;
  dateLastLogin: string | null;
  externalId: string | null;
  zltoWalletId: string | null;
  zltoWalletCountryId: string | null;
  zltoWalletCountryCodeAlpha2: string | null;
  tenantId: string | null;
  dateCreated: string;
  dateModified: string;

**Comment by liquidsurfer** [comment]
Youth have the ability to share their profile in the form of a QR. During this process, they select credentials/items from their CV they would like to share. Therefore creds, and some user data should be marked as shareable or not to indicate what is pulled through on the live profile.

https://www.figma.com/file/RI9Bdjeia0PxJGxxDnIQ6y/Yoma-Youth-Re-Design?type=design&node-id=9879-107370&mode=design&t=0Og2D9YbtXs0j1mm-4

**Comment by liquidsurfer** [comment]
Add: country code for phone number?

**Comment by liquidsurfer** [comment]
@adrianwium - we will need to think about roles:

1. Admin
2. OP/Partner/Provider
3. User

Perhaps the OP role is covered by the Org having an admin assigned to the user? But just something to think about.

**Comment by adrianwium** [comment]
Phone number regex supports country codes
Verified data structure
Support user roles: User, Admin & Organization Admin
