### ISSUE TITLE
Organisation Schema

### ISSUE THREAD

**Issue by liquidsurfer** [didx-xyz/yoma#38]

**Comment by liquidsurfer** [comment]
We only have the concept of approved or not (bool) currently. Will then have to introduce a status (pending, approved, declined). We can then do as stated, and delete declined orgs after 30 days.
Active will remain a sperate concept. Approved can be deactivate at a later state. Pending and declined will implicitly be inactive



Will require a scheduled job to cleanup declined's after 30days

Combine the statuses, similar to opportunities, namely inactive (or pending), active (or approved), declined

**Comment by adrianwium** [comment]
Final status logic:

Inactive - Default status upon creation
Active - Approved and visible to Youth
Declined - Explicitly declined or auto declined within 30 days, provided inactive
Deleted - Explicitly deleted or auto deleted within 30 days, provided declined

Deleted records permanently removed after 30 days, provided not referenced
