### ISSUE TITLE
Opportunity Schema

### ISSUE THREAD

**Issue by liquidsurfer** [didx-xyz/yoma#40]
**GENERAL**

- OrgID
- Title
- Language (offered in)
- Description
- Type (learning/task)
- Category
- Instructions (pending)
- Link URL
- Country avail in (worldwide or multiselect)
- ZLTO reward
- Yoma Reward
- Verification required boolean
- Difficulty
- Start date
- End date
- No end date boolean
- Commitment int
- Commitment timeframe
- Skills (EMSI framework likely to change)
- Participation limit
- Keywords (array)

**SSI (TBC)**

- Schema
- Verification policy

**Comment by adrianwium** [comment]
Verified data structures

**Comment by liquidsurfer** [comment]
Opportunity status = expired. 

This is when completing/engaging with the opportunity is not possible, but Youth can still apply for verification. 

This status should be active when the opportunity end date equals today. Expired status should happen for 30 days, before being make 'inactive'

Behaviour for expired:
- Expired tag on the overview card
- "Go-to-link" button disabled.
- Apply for verification still able.
- After 30 days it should be made hidden/Inactive. 


So overall status':

1. Draft
2. Active
3. Expired (30 days till inactive)
4. Inactive
5. Deleted

**Comment by liquidsurfer** [comment]
Another potential type of opportunity pending is an event. It's not an immediate request but on the horizon.
